function generateACParameters_less_temp(filename, num_devices_ac)
    % 修改版：支持自定义输出文件名，并增加 P_max_cold 参数
    if nargin < 4, residential_ratio = 0.5; end
    
    %% AC 数据生成逻辑
    acParams = struct('Tmin', 23, 'Tmax', 26, 'R_range', [2.0, 3.0], 'C_range', [0.4, 0.7]);
    
    % 定义三种空调的最大制冷功率选项 (单位: kW)
    % 对应 1700W, 3550W, 5500W
    P_options = [1.7; 3.55; 5.5]; 
    
    % 为每台设备随机选择一个功率索引 (1, 2, 或 3)
    rand_indices = randi(3, num_devices_ac, 1);
    
    % 根据索引获取对应的功率值
    P_max_selected = P_options(3);

    acData = struct(...
        'ID', num2cell(1:num_devices_ac)',...
        'R', num2cell(round(acParams.R_range(1) + diff(acParams.R_range)*rand(num_devices_ac,1), 2)),...
        'C', num2cell(round(acParams.C_range(1) + diff(acParams.C_range)*rand(num_devices_ac,1), 2)),...
        'eta', num2cell(round(0.85 + 0.1*rand(num_devices_ac,1), 2)),...
        'Tset', num2cell(round(acParams.Tmin + (acParams.Tmax-acParams.Tmin)*rand(num_devices_ac,1), 1)),...
        'Tmax', num2cell(repmat(acParams.Tmax, num_devices_ac,1)),...
        'Tmin', num2cell(repmat(acParams.Tmin, num_devices_ac,1)),...
        'SOC', num2cell(round(0.5*rand(num_devices_ac,1), 2)),...
        'p_incentive', num2cell(round(60*rand(num_devices_ac,1), 1)),...
        'P_max_cold', num2cell(P_max_selected)... % 新增：最大制冷功率 (kW)
    );
    
    % 仅写入 AC 数据到指定文件
    writetable(struct2table(acData), filename);
end