function generateACParameters(filename, num_devices_ac)
    % 修改版：支持自定义输出文件名
    if nargin < 4, residential_ratio = 0.5; end
    
    %% AC 数据生成逻辑 (保持原逻辑不变)
    acParams = struct('Tmin', 18, 'Tmax', 26, 'R_range', [1.5, 3.0], 'C_range', [0.3, 0.7]);
    acData = struct(...
        'ID', num2cell(1:num_devices_ac)',...
        'R', num2cell(round(acParams.R_range(1) + diff(acParams.R_range)*rand(num_devices_ac,1), 2)),...
        'C', num2cell(round(acParams.C_range(1) + diff(acParams.C_range)*rand(num_devices_ac,1), 2)),...
        'eta', num2cell(round(0.85 + 0.1*rand(num_devices_ac,1), 2)),...
        'Tset', num2cell(round(acParams.Tmin + (acParams.Tmax-acParams.Tmin)*rand(num_devices_ac,1), 1)),...
        'Tmax', num2cell(repmat(acParams.Tmax, num_devices_ac,1)),...
        'Tmin', num2cell(repmat(acParams.Tmin, num_devices_ac,1)),...
        'SOC', num2cell(round(0.5*rand(num_devices_ac,1), 2)),...
        'p_incentive', num2cell(round(60*rand(num_devices_ac,1), 1))...
    );
    
    % 仅写入 AC 数据到指定文件
    writetable(struct2table(acData), filename);
end